(DOCSP-19437): mongosh telemetry
mongodb/docs-mongodb-shell pull request #169
Opened 2021-11-17 20:24 UTC by jeff-allen-mongo

Hi @addaleax , @mmarcon.

This update adds documentation for telemetry in mongosh. Would you mind taking a look when you have a chance?

JIRA:

https://jira.mongodb.org/browse/DOCSP-19437

STAGING:

[Configure Telemetry](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-19437/telemetry/)

[Telemetry Methods](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-19437/reference/methods/#telemetry-methods)

2021-11-18 08:12 UTC, mmarcon commented
LGTM. I also asked Rachael to take a look.

2021-11-18 10:18 UTC, addaleax approved these changes

2021-11-19 16:30 UTC, mmarcon requested changes
Other than the change I suggested, LGTM.

2021-11-19 16:30 UTC, mmarcon commented on source/telemetry.txt
> +``mongosh`` collects anonymous usage data to improve MongoDB products.
```suggestion
``mongosh`` collects anonymous and aggregated usage data to improve MongoDB products.
```
Small tweak suggested by Rachael.

2021-11-19 18:10 UTC, merged