DOCSP-17144 compatibility via snippet
mongodb/docs-mongodb-shell pull request #225
Opened 2022-07-20 15:41 UTC by davemungo

[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/mongodb-shell/docsworker-xlarge/DOCSP-17144-compatibility-via-snippet/reference/compatibility/)

[JIRA](https://jira.mongodb.org/browse/DOCSP-17144)

2022-07-20 16:45 UTC, jason-price-mongodb commented on source/reference/compatibility.txt
> +This page addresses differences between ``mongosh`` and the legacy
"This page describes ..."

2022-07-20 17:33 UTC, davemungo commented on source/reference/compatibility.txt
> +This page addresses differences between ``mongosh`` and the legacy
Done

2022-07-20 17:39 UTC, davemungo commented on source/reference/compatibility.txt
> +snippet to access to legacy :binary:`mongo` shell APIs. For more
It's ok in this context - "snippets" are a mini feature in mongosh, sort of like plug-ins or extensions.

2022-07-20 17:56 UTC, jason-price-mongodb commented
@davemungo LGTM.

2022-07-20 17:57 UTC, davemungo commented
@mmarcon would you take a look at this PR when you have a moment?

2022-07-22 06:52 UTC, mmarcon requested changes

2022-07-22 06:52 UTC, mmarcon commented on source/reference/compatibility.txt
> +<https://github.com/mongodb-labs/mongosh-snippets/blob/main/snippets/mongocompat/index.js>`__
```suggestion
<https://github.com/mongodb-labs/mongosh-snippets/tree/main/snippets/mongocompat>`__
```
I'd link to the root folder in the repo where the README file is.

2022-07-22 06:52 UTC, mmarcon commented on source/reference/compatibility.txt
> +snippet install analyze-schema
```suggestion
snippet install mongocompat
```
Can we show this as a code snippet?

2022-08-01 15:13 UTC, davemungo reviewed
@mmarcon thanks for your feedback.

This is ready for another pass.

2022-08-03 14:30 UTC, addaleax approved these changes

2022-08-03 16:03 UTC, merged