add section explaining the use of the exit() method
mongodb/docs-mongodb-shell pull request #314
Opened 2024-02-01 18:35 UTC by MongoCaleb

## DESCRIPTION
Adds information about how to exit a running script on exception or unexpected results.

## STAGING
https://preview-mongodbmongocaleb.gatsbyjs.io/mongodb-shell/DOCSP-26043/write-scripts/#terminate-a-script-on-error

## JIRA
https://jira.mongodb.org/browse/DOCSP-26043

## BUILD LOG
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bbe37c6b2f17c95ac6db1e

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-02-01 22:33 UTC, mmaville-mdb approved these changes
LGTM!

2024-02-13 12:22 UTC, mmarcon requested changes

2024-02-13 12:22 UTC, mmarcon commented on source/write-scripts.txt
> +``exit`` method in the ``catch`` block. Likewise, to check the results of a query,
```suggestion
``exit`` method in the ``catch`` block. Likewise, to check the results of a query or any command, 
```

this is not specific to queries.

2024-02-14 09:27 UTC, mmarcon approved these changes

2024-02-14 21:48 UTC, merged