DOCSP-37598-mongodb-shell-2.20-release
mongodb/docs-mongodb-shell pull request #325
Opened 2024-03-19 16:41 UTC by mmaville-mdb

## DESCRIPTION
Release Notes for MongoDB Shell 2.2.0. Please note this was originally submitted as 2.1.6 and upreved to 2.2.0 after adding some additional work items.

## STAGING
https://preview-mongodbmmavillemdb.gatsbyjs.io/mongodb-shell/DOCSP-37598-mongodb-shell-2.20-release/changelog/

## JIRA
https://jira.mongodb.org/browse/DOCSP-37598

## BUILD LOG
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f9bdec6fc5f04850f46e28

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

2024-03-19 17:00 UTC, kennethdyer requested changes
Thanks for this work @mmaville-mdb, I left some comments for your consideration.

2024-03-19 17:41 UTC, mmaville-mdb commented on source/changelog.txt
> +- :issue:`MONGOSH-1605` – ``mongosh`` now makes use of Node.js startup
Simplified to "uses" since "now uses... again" felt a bit clunky after seeing the edit.

2024-03-19 17:54 UTC, kennethdyer approved these changes
Thanks @mmaville-mdb, LGTM

2024-03-20 20:20 UTC, kennethdyer reviewed
Thanks @mmaville-mdb.  Left a couple comments for your consideration.

2024-03-20 20:20 UTC, kennethdyer commented on source/changelog.txt
> +     caused an error in script mode.
I don't see a build error for this and the rendering seems ballpark right, so maybe Snooty is making some adjustments, but the indentation looks wrong.

There should be a blank line after the directive.   Lines under the directive should have three space indents to bring them in line with the first letter of the directive type.

2024-03-20 20:20 UTC, kennethdyer commented on source/changelog.txt
> +.. important::
[Suggestion]

Given that we're highlighting a bug, the `warning` direcive may be more appropriate.

2024-03-20 21:03 UTC, mmaville-mdb commented
@GaurabAryal gave approval via Slack on 3/20/24.

2024-03-20 21:19 UTC, merged